title: What have we here
author: EP 
email: erin.p@hotmail.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Hello and welcome to my fun blog full of fun things hope you enjoy thanks for coming haste ye back

# social links
twitter_username: philleepo
github_username:  erin555

show_excerpts: true # set to false to remove excerpts on the homepage

theme: minima
